version: '3.8'

services:
  url-shortener:
    image: emjayfactor507/url-shortener:latest
    container_name: url-shortener-app
    ports:
      - "8080:8080"
    environment:
      # MongoDB Configuration
      - SPRING_DATA_MONGODB_URI=mongodb+srv://emjayfactor:PvjCGKYirwmBr0Nu@maincluster.rxdiylj.mongodb.net/?retryWrites=true&w=majority&appName=MainCluster
      - SPRING_DATA_MONGODB_DATABASE=url_shortener
      # Logging Configuration
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_COM_MJFACTOR=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - url-shortener-network

networks:
  url-shortener-network:

